calblueprint/unloop

app/models/participant.rb
app/models/personal_questionnaire.rb
app/models/professional_questionnaire.rb
db/migrate/20191011034112_create_personal_questionnaires.rb
db/migrate/20191011034236_create_professional_questionnaires.rb
db/migrate/20191011034834_add_questionnaire_to_participant.rb
db/schema.rb

Questionnaire Models
Created the Personal Questionnaire Model and the Professional Questionnaire Model
Two tables were added to the database
Tested belongs_to and has_one relationships with participants.
CC: @adowski

added questionnaire models

---

internals/generators/class/index.js
internals/generators/class/index.js.hbs
internals/generators/functional/index.js
internals/generators/functional/index.js.hbs

Give choice to add ThemeProvider to functional and class components.
Give choice to add headers to functional components.
CC: @adowski

Fix generators to give choice

---

app/javascript/components/PaperworkEntry/index.js
app/javascript/components/PaperworkForm/index.js

Fixed broken paperwork edit functionality

Paperwork Edit Fix

---

db/seeds.rb

Edited Unloop Staff seed so that it also has admin capabilities
Everyone has to reseed the database

Alison/Update Unloop Staff Seed

---

.github/pull_request_template.md
README.md

Update README.md to include credentials info

Update README.md to include credentials info

---

app/javascript/components/Navbar/index.js

No functional changes in this PR. Made Navbar functional component instead of class component since we are switching all small-scale components to be functional.
CC: @didvi

Switched Navbar component from class to functional component

---

app/models/action_item.rb
app/models/assignment.rb
app/models/user.rb
db/migrate/20200229004029_create_action_items.rb
db/migrate/20200301011112_create_assignments.rb
db/migrate/20200301015408_add_assocation_between_assignments_and_users.rb
db/migrate/20200302075639_made_action_item_template_default_false.rb
db/migrate/20200306060137_add_due_date_to_action_items.rb
db/migrate/20200306060137_add_due_date_to_assignments.rb
db/schema.rb
db/seeds.rb
spec/models/action_item_spec.rb
spec/models/assignment_spec.rb

Added Action Items to Database.
This was done through two models: Assignments and Action Items.
The Action Items model contains the title and description of the Action Item and a boolean on whether or not the Action Item is a template. A non-template Action Item has many Assignments pointing to it. Action Items that are templates should not have any Assignments pointing to them. Instead, when a template Action Item is used, a copy of that template should be created with its `is_template` field set to false and Assignments will point to the newly created copy of the template.
Assignment validation (a participant can not assign another participant an action item) currently occurs in the Assignments class through the `valid_assignment` method. This logic can later be moved to a controller if …

Add Action Items to Database

---

app/policies/action_item_policy.rb
app/policies/application_policy.rb
app/policies/assignment_policy.rb
app/policies/studio_assessment_policy.rb

Created Pundits for Assignments, ActionItems, and StudioAssessments. Assignments and StudioAssessments have scope controls that restrict participants to only seeing their own Assignments and StudioAssessments.
CC: @didvi

Create Pundits for Assignments, ActionItems, and StudioAssessments

---

app/controllers/api/case_notes_controller.rb
app/controllers/pages_controller.rb
app/javascript/components/CaseNoteCard/index.js
app/javascript/components/CaseNoteContainer/index.js
app/javascript/components/CaseNoteForm/index.js
app/models/case_note.rb
app/policies/case_note_policy.rb
app/serializers/case_note_serializer.rb
app/views/case_notes/edit.html.erb
app/views/case_notes/index.html.erb
app/views/case_notes/new.html.erb
app/views/case_notes/show.html.erb
config/routes.rb
db/migrate/20191004042135_create_case_notes.rb
db/migrate/20200330025821_casenotes_rename_internal_to_visible.rb
db/schema.rb
db/seeds.rb

Changed internal column in casenotes model to visible
Fixed issue with inconsistent visibility on participant end
Optional - any related PRs you're waiting on, or PRs that will conflict, etc
Optional - if you added anything to the database through migration(s)
Optional but would be nice for final presentation :)
CC: @didvi

Casenotes Refactoring

---

app/javascript/utils/theme.js

I added the changes you made in your WIP PR so that people doing styling right now can start to use them. 
CC: @julianrkung

Added to Theme.js

---

Gemfile
Gemfile.lock
app/controllers/api/assignments_controller.rb
app/controllers/api/case_notes_controller.rb
app/controllers/api/paperworks_controller.rb
app/controllers/api/personal_questionnaires_controller.rb
app/controllers/api/professional_questionnaires_controller.rb
app/controllers/application_controller.rb
app/controllers/assignments_controller.rb
app/controllers/case_notes_controller.rb
app/controllers/paperworks_controller.rb
app/controllers/studio_assessments_controller.rb
app/javascript/components/CaseNoteForm/index.js
app/javascript/components/DeleteModal/index.js
app/javascript/components/Navbar/index.js
app/javascript/components/PaperworkEntry/index.js
app/javascript/components/PaperworkForm/index.js
app/javascript/components/QuestionnaireForm/index.js
app/javascript/packs/application.js
app/javascript/utils/axios.js
app/javascript/utils/logger.js
app/views/layouts/application.html.erb
config/application.rb
package.json
yarn.lock

Add Sentry for Rails and React
Adding pictures of a Destroy CaseNote Error. I've included additonal details like CaseNote attributes, Participant/Staff information, and Current user information
Error:
User:
CaseNote, Participant, Staff info:
CC: @didvi @FranCogMents

Add Sentry for Rails and React

---

app/views/layouts/application.html.erb

Allows us to replay session during bug bash:
To test I deployed fullstory branch to unloop-staging heroku and after playing on the website for a bit, the sessions showed up!

Integrated Fullstory into app

---

app/models/case_note.rb
app/models/paperwork.rb

Fixed admin bug

---

app/javascript/components/ParticipantShowPage/index.js

No functional changes. Fix button alignment. See photos.
Before:
After:
CC: @didvi

Fixed button alignment on top of paperworks list

---

app/javascript/components/ActionItemCard/index.js
app/javascript/components/ActionItemCreationContainer/index.js
app/javascript/components/ActionItemCreationPage/index.js
app/javascript/components/ActionItemList/index.js
app/javascript/components/AddFromExistingForm/index.js

As title says. Before this PR, the Action Item template would disappear from being displayed on the right side when selected. When the `+` is clicked, the ActionItemTemplate is selected and the `+` turns into a checkmark as the screenshot displays. If the checkmark is clicked, the ActionItemTemplate is deselected and it disappears from the left side (the checkmark also turns back into a plus).
Run and select / deselect templates
CC: @didvi

Template Action Items display checkmark when selected

---

app/javascript/components/ActionItemForm/index.js

Checkbox resets to false yuh yuh.
CC: @didvi

ActionItemForm checkbox resets after assignment creation

---

app/javascript/components/ParticipantCard/index.js
app/javascript/components/ParticipantCard/styles.js

status icons on main dashboard#

---

app/controllers/pages_controller.rb
app/javascript/components/ParticipantCard/index.js
app/javascript/components/StaffDashboard/index.js

Describe your feature here
Optional - any related PRs you're waiting on, or PRs that will conflict, etc
Optional - if you added anything to the database through migration(s)
Optional but would be nice for final presentation :)
CC: @didvi

added assessments to dashboard

---

app.json

`rails db:schema:load` was breaking the deployment of review apps so just removing it all together
CC: @didvi

Fix postdeploy script to use migrate

---

app/javascript/components/ViewMoreModal/index.js

but at what cost?
If there exists a due date:
If not:
CC: @didvi

Added due date in view more modal.

---

app/controllers/studio_assessments_controller.rb
app/policies/studio_assessment_policy.rb

Studio assessments dashboard is only visible to staff members now.

fixed auth for studio assessments

---

app/javascript/components/ActionItemCard/index.js
app/javascript/components/ActionItemCategoryTag/index.js
app/javascript/components/ActionItemCategoryTag/styles.js
app/javascript/components/ActionItemCreationContainer/index.js
app/javascript/components/ActionItemCreationPage/index.js
app/javascript/components/ActionItemForm/index.js
app/javascript/components/AddFromExistingForm/index.js
app/javascript/components/ViewMoreModal/index.js
app/javascript/utils/utils.js
app/views/assignments/index.html.erb

Also some small styling changes about spacing of the tag in the AddFromExisting form and the ActionItemCard.
I'd prefer this to get merged decently quickly since I want to append to the new utils file I made in this PR.
CC: @didvi

Made Category Tag its own component + not clickable when appropriate

---

app/javascript/components/ActionItemCreationPage/index.js
app/javascript/components/AddFromExistingForm/index.js
app/javascript/components/LoadModal/index.js

Added focus to the two screenshotted buttons below on modal popup.
It's pretty darn lit. Try it out.
CC: @didvi

Apply focus on buttons when modal pops up

---

app/javascript/components/ActionItemCreationPage/index.js
app/javascript/components/ActionItemSearchParticipants/index.js
app/javascript/components/AddFromExistingForm/index.js
app/javascript/components/LoadModal/index.js

As name implies. Also fixed a warning about wrong proptype verification for ActionItemSearchParticipants
You can click out of this modal now
CC: @didvi

Click out of submission modal if it errors

---

app/javascript/components/StudioAssessmentQuestion/index.js
app/javascript/components/StudioAssessmentQuestion/questions.js

fixed rubric item question order

questions fixed#

---

app/javascript/components/ActionItemCreationPage/index.js

No functional changes. Just refactor. The code was ugly and i made it in haste before bug bash. i apologize.
Pull and navigation buttons should work as normal (save & continue & back & assign)
CC: @didvi

[Easy] Refactored getButtons function in assignments component

---

app/javascript/components/ParticipantShowPage/index.js
app/javascript/components/ParticipantShowPage/styles.js

participant status icon

---

app/javascript/components/ActionItemCategoryTag/styles.js
app/javascript/components/ActionItemForm/index.js
app/javascript/components/ActionItemModal/index.js
app/views/assignment_mailer/new_assignment.html.erb
app/views/assignment_mailer/new_assignment.text.erb

also fixed 
- styling that made the longer category names uncentered in the fab
- mailer bug causing action item creation to fail

Switched components in Action Item Modal to use Category Tag component

---

app/javascript/components/EnhancedTable/index.js
app/javascript/components/StaffDashboard/index.js
app/javascript/components/StudioAssessmentDashboard/index.js

fixes bug that shows no results for search when not on page 1 of the dashboard

Dashboard search bug fix

---

app/controllers/api/assignments_controller.rb

Template creation yuh yuh
CC: @didvi

Creating template without file patch

---

app/controllers/api/assignments_controller.rb
app/models/assignment.rb

Update was not working on participant show page if file was not included. This bug is now fixed.
I also cleaned up some of the logic in the assignments controller, which consisted of:
- removal of semi-duplicate function
- fixed error messages to match app terminology
- moved unclean if statements to the helper function
Hopefully this brings you some joy @julianrkung 
Note:
the due date logic could also be cleaned up imo, but I left it for fear of breaking something

Fixed update bug

---

config/storage.yml

Just added AWS settings for heroku.

aws s3 settings
